import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { IntroGate } from "@/components/blocks/intro-context";
import { ProceduralBackground } from "@/components/blocks/procedural-background";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProceduralBackground />
        <IntroGate>{children}</IntroGate>
      </body>
    </html>
  );
}
